AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Description": "AWS CloudFormation Template for creating an Amazon DMS  instance dms user secret:
Parameters:
  SourceDBName:
    Type: String
    Description: Please provide Source database name.
  Password:
    NoEcho: true
    Type: String
    Description: If Source database is Oracle and has ASM instance provide the dms_user password for database instance,asm instance.
  AccountNumber:
    Type: Number 
    Description: Delta AWS Account Number
  Environment:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /delta/account/environment:1
  blockCode:
    Type: String
    Description: Enter the 10 character Blockcode (in UpperCase) for this RDS instance
    AllowedPattern: '^[A-Z0-9]{10}$'
    ConstraintDescription: The Blockcode must entered in UpperCase and must be 10 characters long
Conditions:
  isEnvDev: !Equals
    - !Ref Environment
    - development
  isEnvSi: !Equals
    - !Ref Environment
    - systems-integration
  isEnvPrd: !Equals
    - !Ref Environment
    - production
Resources:
 # The resource below creates a secret inside AWS Secrets Manager.  The secret contains a default username
 # and a generated password.  Secrets are encrypted using a KMS CMK Key.
 DBSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: Source Database Instance  dms_user with password 
      Description: 'This is the secret  to connect to the Source Onprem Databases using dms_user '
      Name : !Sub ${SourceDBName}-dmsuser-password-${AccountNumber}
      SecretString: !Ref Password
      KmsKeyId: !If [isEnvPrd,arn:aws:kms:us-east-1:022190431571:key/f3ed4f1d-b808-477d-8624-9d8f6c4a6215, !If [isEnvSi, arn:aws:kms:us-east-1:934408279768:key/860f379b-da0a-4860-92b3-d5909033072e , arn:aws:kms:us-east-1:108101204381:key/4a2623c5-583e-4a00-823b-8093c26552e7 ] ]
      Tags:
        - Key: changeGroup
          Value: DBA Oracle Support
        - Key: costCenter
          Value: C8110ATG
        - Key: dataClassification
          Value: confidential
        - Key: uniqueID
          Value: D12345
        - Key: supportGroup
          Value: DBA Oracle Support
        - Key: AccountNumber
          Value: !Ref AccountNumber
        - Key: blockCode
          Value: !Ref blockCode

  #The SecretsManager Secret ResourcePolicy
 DBSecretPolicy:
    Type: AWS::SecretsManager::ResourcePolicy
    Properties:
      BlockPublicPolicy: True
      SecretId: !Ref DBSecret
      ResourcePolicy:
        Version: '2012-10-17'
        Statement:
        
        - Resource: !Ref DBSecret
          Action:
            - secretsmanager:GetSecretValue
      
          Effect: Allow
          Principal:
            AWS: 
              - !Sub arn:aws:iam::${AccountNumber}:role/dms-vpc-role
              - !Sub arn:aws:iam::${AccountNumber}:role/DeveloperPowerUserProvisioner
              - !Sub arn:aws:iam::${AccountNumber}:role/SpokeArtifactDeployer
          Condition:
            StringEquals: 
              aws:PrincipalOrgID: "o-y1jh907v3u"
        - Resource: !Ref DBSecret
          Action:
            - secretsmanager:GetSecretValue
          Effect: Deny
          Principal: 
            AWS: '*'
          Condition:
            StringNotEquals: 
              aws:PrincipalArn:
               - !Sub arn:aws:iam::${AccountNumber}:role/DeveloperPowerUserProvisioner
               - !Sub arn:aws:iam::${AccountNumber}:role/dms-vpc-role
               - !Sub arn:aws:iam::${AccountNumber}:role/SpokeArtifactDeployer
Outputs:
   SecretArn:
     Description: 'Secret Arn'
     Value: !Ref DBSecret
  
       
          
           