AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::SecretsManager-2020-07-23
Description: 'State: Database Secret'

Parameters:
  DBInstanceName:
   Type: String
   Description: The database instance name where this db user is created.
  DBUsername:
    Description: 'The database user name in the DB instance. Ensure that database user names follow standards . Have Application product code in them'
    Type: 'String'
    Default: ''
  DBPassword:
    Description: >-
      Optional password to be used in the secret. Use this if you need to preset the password otherwise a random password is generated.
      You may only provide value for this parameter for testing purposes only. Otherwise, leave this blank.
    Type: 'String'
    Default: ''
    NoEcho: true
  blockCode:
    Type: String
    Description: Enter the 10 character Blockcode in uppercase.
    AllowedPattern: ^[A-Z0-9]{10}$
    ConstraintDescription: The Blockcode must entered in Uppercase and must be 10 characters long 
  ApplicationIAMRole:
    Type: String 
    Description : Please enter name of the IAM role that is created for Application EC2 Profiles. It should be like deltegate-admin-<blockcode> or delegate-admind-AppRole-<blockcode>.
  costCenter:
    Description: The value for the costCenter tag.
    Type: String
    Default: C8110ATG
  uniqueID:
    Description: The value for the iServerID
    Type: String
    Default: D12345
  supportGroup:
    Description: The value for the supportGroup.
    Type: String
    Default: DBA - Oracle Support 
  changeGroup:
    Description: The value for the changeGroup
    Type: String
    Default: DBA - Oracle Support

Resources:
  DBUserSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: 'This is a Secret for Application user id in the Databases '
      Name : !Sub ${DBInstanceName}-${DBUsername}-secret
      SecretString: !Sub '{"username":"${DBUsername}","password":"${DBPassword}"}'
      KmsKeyId: !Sub arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/${DBInstanceName}-dbuser-secret-cmk
      Tags:
        - Key: changeGroup
          Value: !Ref changeGroup
        - Key: costCenter
          Value: !Ref costCenter
        - Key: dataClassification
          Value: internal
        - Key: uniqueID                     
          Value: !Ref uniqueID
        - Key: supportGroup
          Value: !Ref supportGroup
        - Key: blockCode
          Value: !Ref blockCode
        
  DBUserSecretPolicy:
    Type: AWS::SecretsManager::ResourcePolicy
    Properties:
      BlockPublicPolicy: True
      SecretId: !Ref DBUserSecret
      ResourcePolicy:
        Version: '2012-10-17'
        Statement:
        - Resource: !Ref DBUserSecret
          Action:
            - secretsmanager:GetSecretValue
            - secretsmanager:DescribeSecret
            - secretsmanager:PutSecretValue
            - secretsmanager:ListSecrets
            - secretsmanager:TagResource
            - secretsmanager:UntagResource
            - secretsmanager:UpdateSecret
            - secretsmanager:DeleteSecret
          Effect: Allow
          Principal:
            AWS: 
              - !Sub arn:aws:iam::${AWS::AccountId}:role/DBAOperator
              - !Sub arn:aws:iam::${AWS::AccountId}:role/DeveloperPowerUserProvisioner
              - !Sub arn:aws:iam::${AWS::AccountId}:role/${ApplicationIAMRole}
        - Resource: !Ref DBUserSecret
          Action:
            - secretsmanager:GetSecretValue
            - secretsmanager:DescribeSecret
            - secretsmanager:PutSecretValue
            - secretsmanager:ListSecrets
            - secretsmanager:TagResource
            - secretsmanager:UntagResource
            - secretsmanager:UpdateSecret
            - secretsmanager:DeleteSecret
          Effect: Deny
          Principal: 
            AWS: '*'
          Condition:
            StringNotEquals: 
              aws:PrincipalArn:
                - !Sub arn:aws:iam::${AWS::AccountId}:role/DeveloperPowerUserProvisioner
                - !Sub arn:aws:iam::${AWS::AccountId}:role/DBAOperator 
                - !Sub arn:aws:iam::${AWS::AccountId}:role/${ApplicationIAMRole}   
Outputs:
   SecretArn:
     Description: 'Secret Arn'
     Value: !Ref DBUserSecret   