AWSTemplateFormatVersion: 2010-09-09
Description: Template for Deltas Deafult RDS Parameter Group for PostgreSQL RDS instances

Resources:
  postgres:
    Type: 'AWS::RDS::DBParameterGroup'
    Properties:
      Description: Delta Default Postgres Parameter Group
      Family: postgres12
      Tags:
        - Key: Name
          Value: delta-postgres-12
      Parameters:
        rds.force_ssl: 1
        log_min_duration_statement: 250
        ssl_min_protocol_version: TLSv1.2

  PostgresParameterGroupParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /delta/rds/parametergroup/postgres
      Type: String
      Value: !Ref postgres
      Tier: Standard
      Description: SSM Parameter for the name of the Postgres RDS Parameter Group that all Postgres RDS instances should use.
