AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Description": "AWS CloudFormation Template for creating an Amazon DMS  instance:


Parameters:
  SourceDBName:
    Type: String
    Description: Please provide Source database name.
  dmsPassword:
    NoEcho: true
    Type: String
    Description: If Source database is Oracle and has ASM instance provide the dms_user password for database instance,asm instance.
  blockCode:
    Type: String
    Description: Enter the 10 character Blockcode (in UpperCase) for this RDS instance
    AllowedPattern: '^[A-Z0-9]{10}$'
    ConstraintDescription: The Blockcode must entered in UpperCase and must be 10 characters long  
  
Resources:
# The CMK for DMS   
 CMKforSecretfordmsuser:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductName: "KMS CMK"
      ProvisionedProductName: !Sub ${SourceDBName}-dmsuser-mig-cmk
      ProvisioningArtifactName: "1.5"
      ProvisioningParameters:
        - Key: KEYNAME
          Value: !Sub ${SourceDBName}-dmsuser-mig-cmk
        - Key: KEYACCESS1
          Value: DeveloperPowerUserProvisioner
        - Key: KEY1PERMISSIONS
          Value: Both
        - Key: SERVICENAME
          Value: ""
      Tags:
        - Key: changeGroup
          Value: DBA Oracle Support
        - Key: costCenter
          Value: C8110ATG
        - Key: dataClassification
          Value: internal
        - Key: UniqueID
          Value: 12345
        - Key: supportGroup
          Value: DBA Oracle Support
        - Key: AccountID
          Value: !Sub ${AWS::AccountId} 
      
# The resource below creates a secret inside AWS Secrets Manager.  The secret contains a default username
  # and a generated password.  Secrets are encrypted using a KMS CMK Key.
 DBSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: Source DB dms_user password
      Description: 'This is the secret  to connect to the Source Databases using dms_user  '
      KmsKeyId: !GetAtt 'CMKforSecretfordmsuser.Outputs.CMKARN'
      Name : !Sub ${SourceDBName}-dmsuser-password
      SecretString: !Ref dmsPassword
      Tags:
        - Key: changeGroup
          Value: DBA Oracle Support
        - Key: costCenter
          Value: C8110ATG
        - Key: dataClassification
          Value: internal
        - Key: UniqueID
          Value: 12345
        - Key: supportGroup
          Value: DBA Oracle Support
        - Key: AccountID
          Value: !Sub ${AWS::AccountId} 
 #The SecretsManager Secret ResourcePolicy
 DBSecretPolicy:
    Type: AWS::SecretsManager::ResourcePolicy
    Properties:
      BlockPublicPolicy: True
      SecretId: !Ref DBSecret
      ResourcePolicy:
        Version: '2012-10-17'
        Statement:
        - Resource: !Ref DBSecret
          Action:
            - secretsmanager:GetSecretValue
          Effect: Allow
          Principal:
            AWS: 
              - !Sub arn:aws:iam::${AWS::AccountId}:role/dms-vpc-role
              - !Sub arn:aws:iam::${AWS::AccountId}:role/DeveloperPowerUserProvisioner
        - Resource: !Ref DBSecret
          Action:
            - secretsmanager:GetSecretValue
          Effect: Deny
          Principal: 
            AWS: '*'
          Condition:
            StringNotEquals: 
              aws:PrincipalArn:
                - !Sub arn:aws:iam::${AWS::AccountId}:role/dms-vpc-role
                - !Sub arn:aws:iam::${AWS::AccountId}:role/DeveloperPowerUserProvisioner